# version: "3.9"
services:
  db:
    image: postgres:16
    container_name: ecom_db
    environment:
      POSTGRES_DB: ecom
      POSTGRES_USER: ecom_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["-c","shared_buffers=256MB",
              "-c","work_mem=16MB",
              "-c","maintenance_work_mem=128MB",
              "-c","max_connections=50"]
    # Soft caps (Compose v2 CLI supports these)
    mem_limit: 4g
    cpus: 2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecom_user -d ecom"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:4
    container_name: ecom_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    profiles: ["ui"]   # <-- only starts when you ask for profile "ui"

# This block was part of the implementation of Metabase as a dashboard
  # metabase:
  #   image: metabase/metabase:latest
  #   container_name: ecom_metabase
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     # Metabase will save its metadata in Postgres:
  #     MB_DB_TYPE: postgres
  #     MB_DB_HOST: db
  #     MB_DB_PORT: 5432
  #     MB_DB_DBNAME: metabase
  #     MB_DB_USER: metabase_user
  #     MB_DB_PASS: metabase_secret
  #     # Encryption (IMPORTANT):
  #     MB_ENCRYPTION_SECRET: ecommerce_analytics_python_sql
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   profiles: ["bi"]

volumes:
  pgdata:
